### ISSUE TITLE
getting segmentation error while using yara 

### ISSUE THREAD

**Issue by Greatz08** [netspooky/inhale#2]
i followed each step and install everything but when i use inhale than  i get segmentation error in yara so pls help me to fix it.

**Comment by netspooky** [comment]
Did you try this step?

`sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf'`
`sudo ldconfig`

There can sometimes be issues with loading the yara shared object. Please post the full output if this doesn't work.

Also, I am going to be posting some fixes to this repo very soon, started working on it again.
